### ISSUE TITLE
Feature Request: Project Box Creator USB power cord hole

### ISSUE THREAD

**Issue by wokkeltje13** [EvisHome/home-assistant#2]
It would be nice to have more possibilities with the USB power cord hole, maybe just by entering the offset from the bottom and the height of the hole. instead of the orientation of the board.
I have an ESP32mini and the hole is verry big for this small board.

tnx

**Comment by EvisHome** [comment]
Yea that actually sounds a lot better option, will try to add it at some point. 

Meanwhile as a workaround, you can just export the box as a shape without the USB hole and add a "hole" in the TinkerCad 3D design.
