### ISSUE TITLE
Feature Request: enable solderless bottom

### ISSUE THREAD

**Issue by Depechie** [EvisHome/home-assistant#3]
Would it be possible to enable a similar inlay bottom as seen here: [https://www.thingiverse.com/thing:2786523](https://www.thingiverse.com/thing:2786523)
I use this one for all my wled esp8266 projects and it works great, first slot in the cables and then slide in the esp without soldering.

The one I mean is this one:

[https://cdn.thingiverse.com/renders/26/03/d1/b6/c8/14bb56c4723b78d990d9ed06039cab5b_display_large.jpg](https://cdn.thingiverse.com/renders/26/03/d1/b6/c8/14bb56c4723b78d990d9ed06039cab5b_display_large.jpg)

**Comment by EvisHome** [comment]
Not fully sure if I got what you mean. Do you mean you squeeze the wires in to those holes where the ESP pins go in? If so I like the idea, but I don't think it is doable to the current box creator, as there seems to be some "Limits" in the codeblocks .. which I hit while testing the ventilation holes options, if it loops enough and creates "enough holes" you get

"ERROR: Woo, you are doing something crazy, too many primitives are using. Only Allowed: 200"

.. and this would require quite a bit more calculations and loops to create the primitives for the pin holes. 

Perhaps the way to implement would be making a secondary shape or a codeblock to generate the needed pin holes, and then combining that into the generated box in a 3D Editor. Thats how I finalize most of my boxes. I have this self-created "shape library" in TinkerCad for different components and additional options. 

![shape-libary](https://user-images.githubusercontent.com/98347572/196645522-759caf9a-fd1d-40df-8dba-603b79cbf0cb.png)

Sorry,

**Comment by Depechie** [comment]
No worries!
Making an extra component is a logical solution.

And yes you place the wires in the holes and put the ESP on top.

![D5E37E32-EE07-4D2D-8EAD-DC8BCA903BF0](https://user-images.githubusercontent.com/351693/196647962-8c318abb-ecdb-4099-b393-807c9c942e97.jpeg)

**Comment by EvisHome** [comment]
Yea that looks quite neat, for making a codeblock, you would need to define the amount of pins the distance between two pins, and how far apart the right and left header rims are. I'd perhaps would make box shape, then create a "bunch" hole for a pin and the wire, group those holes, loop the hole group for all pins and move in place for one side. Group the shape and just copy the created group and move it to other side.
